language: rust

matrix:
  include:
    # OS compat
    - os: linux
    - os: linux
      arch: arm64
    # As of this writing, stable Rust (1.44.0) and the OS X version on TravisCI
    # do not work well together.
    - os: osx
      rust: 1.43.1

    # rustc version compat
    - rust: 1.41.1 # oldest supported version, keep in sync with README.md
    - rust: 1.41.1
      env: DIST_SCCACHE=1
    - rust: beta
    - rust: nightly

    # deployments
    - env: DEPLOY=1 TARGET=x86_64-apple-darwin OPENSSL_STATIC=yes
      script: cargo build --release --target $TARGET --features=all
      os: osx
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl OPENSSL_DIR=$HOME/openssl-musl
      before_script: ./scripts/travis-musl-openssl.sh
      script: cargo build --release --target $TARGET --features=all
      addons:
        apt:
          packages:
          - musl-tools
    - env: DEPLOY=1 TARGET=aarch64-unknown-linux-musl OPENSSL_DIR=$HOME/openssl-musl CC_aarch64_unknown_linux_musl=musl-gcc
      before_script: ./scripts/travis-musl-openssl.sh
      script: cargo build --release --target $TARGET --features=all
      arch: arm64
      addons:
        apt:
          packages:
          - musl-tools
  allow_failures:
    - rust: nightly

before_script:
  - export EXTRA_FEATURES=
  - if [[ "${TRAVIS_RUST_VERSION}" = "stable" ]]; then rustup component add rustfmt && cargo fmt -- --check; fi
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then export EXTRA_FEATURES="$EXTRA_FEATURES unstable"; fi
  - if [[ "${DIST_SCCACHE}" = "1" ]]; then export EXTRA_FEATURES="$EXTRA_FEATURES dist-client dist-server"; fi

script:
  - cargo build --verbose --features="all ${EXTRA_FEATURES}" || exit 1
  - RUST_BACKTRACE=1 cargo test --all --verbose --no-default-features --features="${EXTRA_FEATURES}" 
  - RUST_BACKTRACE=1 cargo test --all --verbose --features="all ${EXTRA_FEATURES}"
  # Requires PR #321
  #- if [[ "${DIST_SCCACHE}" = "1" ]]; then RUST_BACKTRACE=1 cargo test --all --verbose --features="all dist-tests ${EXTRA_FEATURES}" test_dist_ -- --test-threads 1; fi

before_deploy:
  - "./scripts/prep_deploy.sh"

deploy:
  api_key:
    secure: MNtCnEsg2dB0gbcLY0Jn3zLcTJoSu5AuDqG5HtdUHMFDsodH35xSAP0dWHRdUmQ3+6zg2+22oBLCLaksxNW715/xKHthQZBcPipAycQUUAQy28zKmIENmiUJYSdxdE7m1SRGZ0YqKN2ua5diXPwMMaZNOFq373WzcSCtvazdwJh3TXTWwJXTQJiK34BBw5Qh0jsvNCBrK4I+HROiwgR/wShmOZVYlHxTRzcJqGjw2J+eyz25Ye9jdfUXyIzdQRFBcdCN0WftwqI+XuoLI4gqC/mY/aDg3IqAoMgcbeHZhpKEW3wK64OmGUMbMFkVRM51/IqJ/RhJDUPfN5aC5W10KhKnHkez4jlPKqDEA8scHCNyNcbhF1z2PKj/8msIhsv582oaDQ7g33YSyRHsbc8R2b6LGXKOnuN5CnMG3fK3bJ1vPbutwglEpfIBjAGerUGmNBbeLDz8P+J0jf7ajzp/VzArziMVwGYKs5jsjw9rgX0pvT1Jk6ec9qfQ5pNs7T6AYoUYjZgm1oVioD4V8FUsCe/Gc1himE+uqhZT9D+PbcbmZgcNCwKbjr+b9d3kW8Oa26skU+YVEjnvD4pJ8J9TPAuX9Zglhe9AsXHMXyiZzOcDcAWwdEnfSiwYgA65VkkTzOBNHND/HHgqieTYU6XDl0RMRbzw4Z8w4keDSGpVrgc=
  file_glob: true
  file:
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz.sha256
  on:
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true
